create table search_users_data (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
    birthdate VARCHAR(255),
	gender VARCHAR(255),
	email_address VARCHAR(255),
    phone_number VARCHAR (20),
    applied_position VARCHAR(255),
    start_date VARCHAR(255),
	address VARCHAR(255),
	nationality VARCHAR(255),
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Farand', 'Sylett', '12/16/2023', 'Female', 'fsylett0@fotki.com', '736-898-5766', 'Civil Engineer', '10/27/2024', 'Suite 88', 'Chippewa');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Beth', 'Ashplant', '3/18/2024', 'Female', 'bashplant1@nbcnews.com', '112-381-8386', 'Technical Writer', '6/14/2024', '12th Floor', 'Melanesian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Aleksandr', 'Dagwell', '9/19/2024', 'Male', 'adagwell2@furl.net', '913-233-0689', 'Marketing Manager', '1/8/2024', 'PO Box 44725', 'Potawatomi');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Vergil', 'Jaram', '7/29/2024', 'Male', 'vjaram3@printfriendly.com', '566-278-5189', 'Software Consultant', '11/13/2023', '5th Floor', 'Samoan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Radcliffe', 'Risbridge', '11/3/2024', 'Male', 'rrisbridge4@chicagotribune.com', '381-586-4552', 'Speech Pathologist', '7/9/2024', 'Room 1005', 'Apache');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Vincenty', 'Pavlishchev', '11/26/2023', 'Male', 'vpavlishchev5@ucsd.edu', '189-251-9562', 'Librarian', '4/5/2024', 'Apt 1423', 'Cambodian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Huberto', 'Wieprecht', '9/11/2024', 'Polygender', 'hwieprecht6@ucoz.com', '440-634-5609', 'Office Assistant IV', '1/8/2024', 'PO Box 14753', 'Alaskan Athabascan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Jacquette', 'Lawlan', '8/31/2024', 'Female', 'jlawlan7@wordpress.org', '460-860-8552', 'Mechanical Systems Engineer', '9/18/2024', '12th Floor', 'Bangladeshi');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Lilian', 'Aitkin', '5/25/2024', 'Female', 'laitkin8@spiegel.de', '253-521-4958', 'Office Assistant II', '4/15/2024', 'Suite 42', 'Spaniard');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Alastair', 'Tousy', '3/26/2024', 'Male', 'atousy9@canalblog.com', '371-412-8151', 'Graphic Designer', '5/8/2024', 'Apt 545', 'Alaska Native');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Perkin', 'MacAnelley', '8/8/2024', 'Genderqueer', 'pmacanelleya@typepad.com', '172-393-2252', 'Graphic Designer', '4/29/2024', 'PO Box 5785', 'Melanesian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Luther', 'De Simone', '5/1/2024', 'Male', 'ldesimoneb@wordpress.com', '379-923-0472', 'Statistician III', '10/9/2024', 'Apt 1638', 'Asian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Ania', 'Parres', '1/2/2024', 'Female', 'aparresc@google.it', '766-469-8436', 'Dental Hygienist', '2/21/2024', '13th Floor', 'Dominican (Dominican Republic)');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Theobald', 'Wearne', '2/11/2024', 'Male', 'twearned@sciencedaily.com', '872-216-9199', 'Senior Editor', '12/6/2023', 'Suite 59', 'Panamanian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Ethelda', 'Kippen', '8/18/2024', 'Female', 'ekippene@sogou.com', '854-782-1018', 'Paralegal', '2/9/2024', 'Room 1809', 'Chilean');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Morganne', 'Antoniewski', '9/6/2024', 'Female', 'mantoniewskif@loc.gov', '352-368-6729', 'Quality Engineer', '11/19/2023', 'Suite 51', 'Pakistani');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Aldin', 'Huleatt', '7/9/2024', 'Male', 'ahuleattg@va.gov', '357-686-4255', 'Sales Representative', '8/10/2024', 'Suite 17', 'Micronesian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Ode', 'Stallan', '1/14/2024', 'Male', 'ostallanh@newsvine.com', '578-364-4494', 'Business Systems Development Analyst', '10/12/2024', 'Suite 69', 'Lumbee');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Douglass', 'Blazhevich', '1/14/2024', 'Male', 'dblazhevichi@gnu.org', '933-942-6104', 'VP Accounting', '2/4/2024', 'PO Box 15241', 'Chilean');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Hayyim', 'Berndtsson', '5/22/2024', 'Male', 'hberndtssonj@bloomberg.com', '156-570-7882', 'Account Executive', '9/30/2024', 'Room 1750', 'Houma');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Carla', 'Foulkes', '1/26/2024', 'Female', 'cfoulkesk@mozilla.com', '333-140-2507', 'Biostatistician III', '1/21/2024', 'Room 1723', 'Cambodian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Yehudi', 'Vize', '4/20/2024', 'Male', 'yvizel@boston.com', '699-797-5879', 'Quality Engineer', '12/13/2023', 'Suite 80', 'Crow');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Marjy', 'Gasking', '6/4/2024', 'Agender', 'mgaskingm@pcworld.com', '780-797-3419', 'Teacher', '6/23/2024', 'Room 493', 'Creek');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Ralf', 'Delieu', '5/20/2024', 'Male', 'rdelieun@yolasite.com', '638-681-3556', 'Design Engineer', '10/19/2024', 'Apt 1458', 'Chinese');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Alyssa', 'Chuck', '2/12/2024', 'Female', 'achucko@time.com', '922-318-2727', 'Accounting Assistant III', '4/17/2024', 'Apt 793', 'Eskimo');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Jayne', 'Droogan', '8/11/2024', 'Female', 'jdrooganp@disqus.com', '632-163-3541', 'Librarian', '8/16/2024', 'PO Box 47213', 'Laotian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Emmet', 'Borgnet', '2/29/2024', 'Male', 'eborgnetq@imdb.com', '593-654-5875', 'Operator', '11/7/2023', 'Suite 53', 'Samoan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Bridgette', 'Barthel', '3/22/2024', 'Polygender', 'bbarthelr@fda.gov', '809-749-7151', 'Marketing Manager', '5/25/2024', 'PO Box 25099', 'Creek');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Riva', 'Grosvener', '9/24/2024', 'Bigender', 'rgrosveners@arstechnica.com', '794-339-8969', 'Actuary', '1/20/2024', 'Room 1958', 'Paraguayan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Aloise', 'Satchel', '12/13/2023', 'Female', 'asatchelt@slate.com', '972-167-2844', 'Editor', '11/5/2024', 'Suite 42', 'Iroquois');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Kalinda', 'Sotworth', '11/3/2024', 'Female', 'ksotworthu@who.int', '228-541-0433', 'Quality Control Specialist', '10/28/2024', '5th Floor', 'Tongan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Alyss', 'Rittmeier', '6/25/2024', 'Female', 'arittmeierv@uol.com.br', '788-649-1614', 'Marketing Manager', '2/21/2024', 'Room 613', 'Creek');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Amos', 'Austins', '12/26/2023', 'Male', 'aaustinsw@paginegialle.it', '292-958-0604', 'Senior Editor', '8/31/2024', 'Apt 965', 'Ottawa');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Lilith', 'Dahmke', '10/13/2024', 'Female', 'ldahmkex@biglobe.ne.jp', '210-373-4522', 'Geologist III', '3/13/2024', 'PO Box 52249', 'Dominican (Dominican Republic)');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Mirabelle', 'Crisell', '5/24/2024', 'Female', 'mcriselly@freewebs.com', '214-710-7017', 'Business Systems Development Analyst', '10/11/2024', 'Suite 73', 'Puget Sound Salish');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Elisabeth', 'Cassam', '5/15/2024', 'Female', 'ecassamz@huffingtonpost.com', '501-234-6610', 'Assistant Professor', '2/1/2024', '8th Floor', 'Crow');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Danica', 'Hellmore', '8/8/2024', 'Female', 'dhellmore10@bloglovin.com', '153-849-7498', 'Speech Pathologist', '2/13/2024', 'Suite 78', 'Venezuelan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Clerissa', 'Ubsdall', '7/28/2024', 'Female', 'cubsdall11@thetimes.co.uk', '906-134-7174', 'Senior Quality Engineer', '12/22/2023', 'PO Box 59470', 'Cheyenne');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Mariska', 'Aspell', '11/14/2023', 'Non-binary', 'maspell12@gmpg.org', '799-126-5702', 'Business Systems Development Analyst', '8/11/2024', 'Apt 125', 'Uruguayan');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Barbaraanne', 'Rosenbusch', '7/26/2024', 'Genderfluid', 'brosenbusch13@ted.com', '472-940-0157', 'Chief Design Engineer', '9/2/2024', '18th Floor', 'Iroquois');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Adrien', 'Chezier', '1/25/2024', 'Male', 'achezier14@sbwire.com', '229-113-9664', 'Pharmacist', '2/11/2024', 'PO Box 89007', 'Tlingit-Haida');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Alexandr', 'Walhedd', '2/11/2024', 'Male', 'awalhedd15@omniture.com', '390-509-4278', 'Senior Financial Analyst', '9/6/2024', 'Suite 91', 'Chickasaw');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Sarene', 'Sugden', '9/5/2024', 'Female', 'ssugden16@usa.gov', '424-549-9324', 'Software Test Engineer II', '2/2/2024', 'Apt 3', 'American Indian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Elga', 'Gritten', '6/15/2024', 'Female', 'egritten17@google.co.jp', '252-771-3778', 'Research Assistant III', '1/11/2024', 'Suite 11', 'Polynesian');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Jaimie', 'Mattam', '4/8/2024', 'Female', 'jmattam18@fda.gov', '909-439-7343', 'Community Outreach Specialist', '5/22/2024', '3rd Floor', 'Blackfeet');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Fredra', 'Paprotny', '2/18/2024', 'Female', 'fpaprotny19@java.com', '162-689-1351', 'Help Desk Technician', '2/24/2024', 'Room 1484', 'Osage');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Ferguson', 'Borrell', '8/30/2024', 'Male', 'fborrell1a@latimes.com', '970-843-3970', 'Registered Nurse', '10/29/2024', '17th Floor', 'Creek');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Arlette', 'Yarrall', '6/30/2024', 'Female', 'ayarrall1b@theguardian.com', '901-108-2293', 'Senior Developer', '11/15/2023', '20th Floor', 'Pakistani');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Inigo', 'Greenwood', '7/31/2024', 'Male', 'igreenwood1c@yandex.ru', '569-337-9223', 'Assistant Professor', '11/16/2023', 'Apt 1337', 'Korean');
insert into search_users_data (first_name, last_name, birth_date, gender, email_address, phone_number, applied_position, start_date, address, nationality) values ('Aveline', 'Saltmarsh', '9/8/2024', 'Female', 'asaltmarsh1d@360.cn', '402-222-2658', 'General Manager', '4/27/2024', 'PO Box 14719', 'Colville');